project:
  type: website
  resources:
    - wasm/**
    - assets/data/**

website:
  title: "ggsql"
  description: |
    The home of ggsql. A declarative visualisation language build on top of SQL
    and the grammar of graphics.
  llms-txt: true
  site-url: https://ggsql.org
  repo-url: https://github.com/posit-dev/ggsql
  issue-url: https://github.com/posit-dev/ggsql/issues
  repo-branch: gh-pages
  image: assets/logo.png
  image-alt: |
    The ggsql logo showing a pencil tracing a lineplot with points. The pencil
    handle is made up of the classic database silo icon and is coloured in a
    gradient teal.
  announcement:
    icon: info-circle
    dismissable: true
    content: "ggsql is still in early development and all functionality is subject to change. Read the [alpha-release announcement](https://opensource.posit.co/blog/2026-04-20_ggsql_alpha_release/)"
    type: primary
    position: below-navbar
  twitter-card:
    card-style: summary
  open-graph: true
  search:
    keyboard-shortcut: []
  navbar:
    left:
      - text: Get started
        href: get_started/installation.qmd
      - text: Syntax
        menu:
          - text: Overview
            href: syntax/index.qmd
          - text: "---"
          - text: "`VISUALISE`"
            href: syntax/clause/visualise.qmd
          - text: "`DRAW`"
            href: syntax/clause/draw.qmd
          - text: "`PLACE`"
            href: syntax/clause/place.qmd
          - text: "`SCALE`"
            href: syntax/clause/scale.qmd
          - text: "`FACET`"
            href: syntax/clause/facet.qmd
          - text: "`PROJECT`"
            href: syntax/clause/project.qmd
          - text: "`LABEL`"
            href: syntax/clause/label.qmd
      - text: Gallery
        href: gallery/index.qmd
      - href: faq.qmd
        text: FAQ
      - text: News
        menu:
          - text: "Releases"
          - text: "Version 0.2.7 (alpha)"
            href: https://opensource.posit.co/blog/2026-04-20_ggsql_alpha_release/
    right:
      - text: Playground
        href: wasm/index.html
      - text: '{{< iconify fa7-brands:python title="Python bindings" label="link to Python bindings" size=xl >}}'
        href: http://python.ggsql.org
      - text: '{{< iconify fa7-brands:r-project title="R bindings" label="link to R bindings" size=xl >}}'
        href: https://r.ggsql.org
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/posit-dev/ggsql
          - text: Report a Bug
            href: https://github.com/posit-dev/ggsql/issues
  sidebar:
    - id: syntax
      title: Syntax
      style: "floating"
      search: true
      logo: false
      contents:
        - text: Overview
          href: syntax/index.qmd
        - section: "Main clauses"
          contents:
            - text: "`VISUALISE`"
              href: syntax/clause/visualise.qmd
            - text: "`DRAW`"
              href: syntax/clause/draw.qmd
            - text: "`PLACE`"
              href: syntax/clause/place.qmd
            - text: "`SCALE`"
              href: syntax/clause/scale.qmd
            - text: "`FACET`"
              href: syntax/clause/facet.qmd
            - text: "`PROJECT`"
              href: syntax/clause/project.qmd
            - text: "`LABEL`"
              href: syntax/clause/label.qmd
        - section: Layers
          contents:
            - section: Types
              contents:
                - auto: syntax/layer/type/*
            - section: Position adjustment
              contents:
                - auto: syntax/layer/position/*
        - section: Scales
          contents:
            - section: Types
              contents:
                - auto: syntax/scale/type/*
            - section: Aesthetics
              contents:
                - auto: syntax/scale/aesthetic/*
        - section: Coordinate systems
          contents:
            - auto: syntax/coord/*
    - id: get_started
      title: Get started
      style: "floating"
      search: false
      logo: false
      contents:
        - text: Installation
          href: get_started/installation.qmd
        - text: The first plot
          href: get_started/first_plot.qmd
        - text: Grammar of graphics
          href: get_started/grammar.qmd
        - text: Anatomy of ggsql
          href: get_started/anatomy.qmd
        - text: Tooling
          href: get_started/tooling.qmd
        - text: The rest of the owl
          href: get_started/the_rest.qmd

format:
  html:
    lightbox: auto
    highlight-style: pygments
    syntax-definitions:
      - ggsql.xml
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/gh/posit-dev/supported-by-posit/js/badge.min.js"
              data-light-bg="#94D2BD"
              data-dark-bg="#001219"></script>
          <!-- Privacy-friendly analytics by Plausible -->
          <script async src="https://plausible.io/js/pa-eH2pS73nQmBLURrhxXgML.js"></script>
          <script>
              window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
              plausible.init()
          </script>
    include-after-body:
      - text: |
          <script type="module">
            const offset = document.querySelector('meta[name="quarto:offset"]')?.content || './';
            const base = offset + 'wasm/';
            const link = document.createElement('link');
            link.rel = 'stylesheet';
            link.href = base + 'quarto.css';
            document.head.appendChild(link);
            import(base + 'quarto.js');
          </script>
